import {chromium} from 'playwright';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://localhost:4322';const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const failures=[];let leaked=0;page.on('request',r=>{if(r.method()==='POST'||r.url().includes('test-gate%40')||r.url().includes('test-gate@'))leaked++;});
try{
 await page.goto(base+'/resources/');await page.getByRole('button',{name:'Data sheet',exact:true}).click();assert.equal(await page.locator('.resource-card:visible').count(),1);await page.locator('.resource-card:visible a').click();assert.equal(new URL(page.url()).pathname,'/resources/platform-data-sheet/');
 assert.equal(await page.locator('[data-gate-result]').isVisible(),false);await page.getByRole('button',{name:'View the data sheet',exact:true}).click();assert.equal(await page.locator('[data-gate-result]').isVisible(),false);
 await page.screenshot({path:'artifacts/data-sheet-gate-desktop.png'});
 for(const [id,value]of [['resource-first-name','Alex'],['resource-last-name','Morgan'],['resource-email','test-gate@example.com'],['resource-company','Example']])await page.locator('#'+id).fill(value);
 await page.getByRole('button',{name:'View the data sheet',exact:true}).click();await page.waitForTimeout(900);assert.equal(await page.locator('[data-gate-result]').isVisible(),true);assert.equal(await page.locator('#resource-email').inputValue(),'');assert.equal(leaked,0);assert.equal(await page.locator('#resource-access-title').evaluate(el=>el===document.activeElement),true);assert.equal(await page.locator('main h1:visible').count(),1);const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();failures.push(...audit.violations);await page.screenshot({path:'artifacts/data-sheet-revealed.png',fullPage:true});
 const response=await page.request.get(base+'/downloads/tracegate-platform-data-sheet.pdf');assert.equal(response.status(),200);assert.ok((await response.body()).subarray(0,4).toString()==='%PDF');
 await page.getByRole('button',{name:'Try the form again'}).click();assert.equal(await page.locator('[data-gate-result]').isVisible(),false);assert.equal(await page.locator('#resource-first-name').evaluate(el=>el===document.activeElement),true);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/data-sheet-gate-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 for(const [route,count]of [['/blog/attack-path-analysis/',2],['/blog/machine-identity-security/',2],['/blog/cspm-vs-attack-paths/',2],['/resources/attack-path-review/',1],['/resources/least-privilege-playbook/',1]]){await page.goto(base+route);assert.equal(await page.locator('.editorial-figure').count(),count);assert.equal(await page.locator('.editorial-inline-cta').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/blog/cspm-vs-attack-paths/');await page.locator('.editorial-figure').first().scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/editorial-inline-diagram.png'});
 await page.goto(base+'/products/attack-paths/');const details=page.locator('.detail-accordion details').first(),summary=details.locator('summary');await summary.click();await page.waitForTimeout(50);assert.equal(await details.locator('.accordion-content').evaluate(el=>el.getAnimations().length>0),true);await page.waitForTimeout(350);assert.equal(await details.getAttribute('open')!==null,true);await summary.click();await page.waitForTimeout(380);assert.equal(await details.getAttribute('open'),null);await summary.click();await page.waitForTimeout(30);await summary.click();await page.waitForTimeout(380);assert.equal(await details.getAttribute('open'),null,'rapid toggle settles closed');await summary.focus();await page.keyboard.press('Enter');await page.waitForTimeout(380);assert.equal(await details.getAttribute('open')!==null,true);
 await page.emulateMedia({reducedMotion:'reduce'});await summary.click();assert.equal(await details.getAttribute('open'),null);assert.equal(await details.locator('.accordion-content').evaluate(el=>el.getAnimations().length),0);
 const nojs=await browser.newContext({javaScriptEnabled:false});const fallback=await nojs.newPage();await fallback.goto(base+'/resources/platform-data-sheet/');assert.equal(await fallback.locator('noscript a').getAttribute('href'),'/downloads/tracegate-platform-data-sheet.pdf');await fallback.goto(base+'/products/attack-paths/');await fallback.locator('.faq summary').first().click();assert.equal(await fallback.locator('.faq details').first().getAttribute('open')!==null,true);await nojs.close();
 assert.equal(failures.length,0);fs.writeFileSync('artifacts/resource-verification.json',JSON.stringify({demoGate:'pass',noSubmission:'pass',pdf:'pass',resetFocus:'pass',inlineFigures:8,contextualCTAs:5,accordion:'pass',reducedMotion:'pass',noJavaScript:'pass',violations:failures},null,2));console.log('Resource gate, PDF, eight inline diagrams, five CTAs, accordion motion/keyboard/rapid-toggle and fallback checks passed.');
}finally{await browser.close();}
