import fs from 'node:fs';
import path from 'node:path';
import {parseHTML} from 'linkedom';
import {gzipSync} from 'node:zlib';
const root=path.resolve('dist');
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);
const files=walk(root),htmlFiles=files.filter(f=>f.endsWith('.html')),errors=[],titles=new Set(),descriptions=new Set(),docs=new Map();
for(const file of htmlFiles){const {document}=parseHTML(fs.readFileSync(file,'utf8'));docs.set(file,document);const rel=path.relative(root,file);const title=document.querySelector('title')?.textContent;const description=document.querySelector('meta[name="description"]')?.getAttribute('content');if(!title||title.length<30||title.length>60)errors.push(`${rel}: title length ${title?.length}`);if(titles.has(title))errors.push(`${rel}: duplicate title`);titles.add(title);if(!description||description.length<120||description.length>160)errors.push(`${rel}: description length ${description?.length}`);if(descriptions.has(description))errors.push(`${rel}: duplicate description`);descriptions.add(description);if(document.querySelectorAll('main h1').length!==1)errors.push(`${rel}: expected one main H1`);if(!document.querySelector('link[rel="canonical"]'))errors.push(`${rel}: missing canonical`);if(!document.querySelector('meta[property="og:image"]'))errors.push(`${rel}: missing social image`);for(const script of document.querySelectorAll('script[type="application/ld+json"]'))try{JSON.parse(script.textContent);}catch{errors.push(`${rel}: invalid JSON-LD`);}for(const img of document.querySelectorAll('img')){if(!img.hasAttribute('alt'))errors.push(`${rel}: image missing alt`);const src=img.getAttribute('src');if(src?.startsWith('/')&&!fs.existsSync(path.join(root,decodeURIComponent(src.split('?')[0]))))errors.push(`${rel}: missing image asset ${src}`);if(!img.hasAttribute('width')||!img.hasAttribute('height'))errors.push(`${rel}: image dimensions missing`);}if(document.querySelector('main')?.textContent.includes('—'))errors.push(`${rel}: em dash in copy`);}
const inbound=new Set();
for(const [file,document] of docs){const route=file===path.join(root,'index.html')?'/':'/'+path.relative(root,path.dirname(file)).replaceAll(path.sep,'/')+'/';for(const a of document.querySelectorAll('a[href]')){const href=a.getAttribute('href');if(/^(https?:|mailto:|tel:|data:)/.test(href))continue;const u=new URL(href,'https://tracegate.example'+route);let destination=path.join(root,decodeURIComponent(u.pathname));if(u.pathname.endsWith('/'))destination=path.join(destination,'index.html');if(!fs.existsSync(destination)){errors.push(`${path.relative(root,file)}: broken link ${href}`);continue;}if(destination.endsWith('.html'))inbound.add(destination);if(u.hash&&docs.has(destination)&&!docs.get(destination).getElementById(decodeURIComponent(u.hash.slice(1))))errors.push(`${path.relative(root,file)}: missing anchor ${href}`);}}
for(const file of htmlFiles)if(!file.endsWith('404.html')&&!inbound.has(file))errors.push(`${path.relative(root,file)}: orphan page`);
for(const required of ['robots.txt','llms.txt','sitemap-index.xml','sitemap-0.xml','social-card.png','brand/brand-kit.json','downloads/attack-path-review.md','downloads/least-privilege-playbook.md'])if(!fs.existsSync(path.join(root,required)))errors.push('Missing '+required);
const scripts=files.filter(f=>f.endsWith('.js'));const js=scripts.reduce((total,f)=>total+fs.statSync(f).size,0);const jsGzip=scripts.reduce((total,f)=>total+gzipSync(fs.readFileSync(f)).length,0);if(js>20000||jsGzip>6000)errors.push(`Browser JS budget exceeded: ${js} raw / ${jsGzip} gzip (limits: 20000 / 6000)`);
const report={pages:htmlFiles.length,browserJavaScriptBytes:js,browserJavaScriptGzipBytes:jsGzip,errors};fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/static-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(errors.length)process.exit(1);
